### ISSUE TITLE
Maybe not fail on startup if DNS record not found?

### ISSUE THREAD

**Issue by ernoaapa** [harlow/nsqd-discovery#3]
Hi,
thanks for creating `nsqd-discovery`! I'm testing out it to setup nsq on Kubernetes.

I have small issue with it though. Now it fails right away if the given lookup DNS name is not found. This causes problem that when I'm starting up the pod (where all pieces are) starts up, the DNS record get created after the pod started up perfectly. But nsqd-discovery causes the pod startup fail.

It could be so that if the DNS record doesn't found it doesn't fail the startup, it would just start normal 15s. loop. This could be behind some cmd line flag of course.

What do you think?

**Comment by harlow** [comment]
@ernoaapa great question. I went back-and-forth on this a bit, and the decision to require DNS was a bit arbitrary. 

Happy to incorporate your idea. Would you like to create a PR? I'm not sure a flag is needed; we could just remove the line that requires DNS.
